/*
* WhatsApp in Ionic 5 application  (https://github.com/habupagas/ionic-5-WhatsApp)
* Copyright  @2020-present. All right reserved.
* Author: Abubakar Pagas
*/


import { Injectable } from '@angular/core';

@Injectable({
    providedIn: 'root'
})
export class CountryCodeService {

    constructor() { }

    getCountryCode() {
        return [{
            dial_code: "+1"
        }, {
            dial_code: "+972"
        }, {
            dial_code: "+93",
        }, {
            dial_code: "+355",
        }, {
            dial_code: "+213",
        }, {
            dial_code: "+1 684",
        }, {
            dial_code: "+376"
        }, {
            dial_code: "+244",
        }, {
            dial_code: "+1 264",
        }, {
            dial_code: "+1268",
        }, {
            dial_code: "+54",
        }, {
            dial_code: "+374",
        }, {
            dial_code: "+297",
        }, {
            dial_code: "+61",
        }, {
            dial_code: "+43",
        }, {
            dial_code: "+994",
        }, {
            dial_code: "+1 242",
        }, {
            dial_code: "+973",
        }, {
            dial_code: "+880",
        }, {
            dial_code: "+1 246",
        }, {
            dial_code: "+375",
        }, {
            dial_code: "+32",
        }, {
            dial_code: "+501",
        }, {
            dial_code: "+229",
        }, {
            dial_code: "+1 441",
        }, {
            dial_code: "+975",
        }, {
            dial_code: "+387",
        }, {
            dial_code: "+267",
        }, {
            dial_code: "+55",
        }, {
            dial_code: "+246",
        }, {
            dial_code: "+359",
        }, {
            dial_code: "+226",
        }, {
            dial_code: "+257",
        }, {
            dial_code: "+855",
        }, {
            dial_code: "+237",
        }, {
            dial_code: "+1",
        }, {
            dial_code: "+238",
        }, {
            dial_code: "+ 345",
        }, {
            dial_code: "+236",
        }, {
            dial_code: "+56",
        }, {
            dial_code: "+86",
        }, {
            dial_code: "+61",
        }, {
            dial_code: "+57",
        }, {
            dial_code: "+269",
        }, {
            dial_code: "+242",
        }, {
            dial_code: "+682",
        }, {
            dial_code: "+506",
        }, {
            dial_code: "+385",
        }, {
            dial_code: "+537",
        }, {
            dial_code: "+420",
        }, {
            dial_code: "+45",
        }, {
            dial_code: "+253",
        }, {
            dial_code: "+1 767",
        }, {
            dial_code: "+1 849",
        }, {
            dial_code: "+593",
        }, {
            dial_code: "+20",
        }, {
            dial_code: "+503",
        }, {
            dial_code: "+240",
        }, {
            dial_code: "+291",
        }, {
            dial_code: "+372",
        }, {
            dial_code: "+251",
        }, {
            dial_code: "+298",
        }, {
            dial_code: "+358",
        }, {
            dial_code: "+33",
        }, {
            dial_code: "+594",
        }, {
            dial_code: "+689",
        }, {
            dial_code: "+241",
        }, {
            dial_code: "+220",
        }, {
            dial_code: "+995",
        }, {
            dial_code: "+49",
        }, {
            dial_code: "+233",
        }, {
            dial_code: "+350",
        }, {
            dial_code: "+30",
        }, {
            dial_code: "+299",
        }, {
            dial_code: "+1 473",
        }, {
            dial_code: "+590",
        }, {
            dial_code: "+502",
        }, {
            dial_code: "+224",
        }, {
            dial_code: "+245",
        }, {
            dial_code: "+595",
        }, {
            dial_code: "+509",
        }, {
            dial_code: "+504",
        }, {
            dial_code: "+36",
        }, {
            dial_code: "+354",
        }, {
            dial_code: "+91",
        }, {
            dial_code: "+62",
        }, {
            dial_code: "+353",
        }, {
            dial_code: "+972",
        }, {
            dial_code: "+39",
        }, {
            dial_code: "+1 876",
        }, {
            dial_code: "+81",
        }, {
            dial_code: "+962",
        }, {
            dial_code: "+7 7",
        }, {
            dial_code: "+254",
        }, {
            dial_code: "+686",
        }, {
            dial_code: "+965",
        }, {
            dial_code: "+996",
        }, {
            dial_code: "+371",
        }, {
            dial_code: "+961",
        }, {
            dial_code: "+266",
        }, {
            dial_code: "+231",
        }, {
            dial_code: "+423",
        }, {
            dial_code: "+370",
        }, {
            dial_code: "+352",
        }, {
            dial_code: "+261",
        }, {
            dial_code: "+265",
        }, {
            dial_code: "+60",
        }, {
            dial_code: "+960",
        }, {
            dial_code: "+356",
        }, {
            dial_code: "+692",
        }, {
            dial_code: "+596",
        }, {
            dial_code: "+222",
        }, {
            dial_code: "+230",
        }, {
            dial_code: "+262",
        }, {
            dial_code: "+52",
        }, {
            dial_code: "+377",
        }, {
            dial_code: "+976",
        }, {
            dial_code: "+382",
        }, {
            dial_code: "+1664",
        }, {
            dial_code: "+212",
        }, {
            dial_code: "+95",
        }, {
            dial_code: "+264",
        }, {
            dial_code: "+674",
        }, {
            dial_code: "+977",
        }, {
            dial_code: "+31",
        }, {
            dial_code: "+599",
        }, {
            dial_code: "+687",
        }, {
            dial_code: "+64",
        }, {
            dial_code: "+505",
        }, {
            dial_code: "+227",
        }, {
            dial_code: "+234",
        }, {
            dial_code: "+672",
        }, {
            dial_code: "+1 670",
        }, {
            dial_code: "+47",
        }, {
            dial_code: "+92",
        }, {
            dial_code: "+680",
        }, {
            dial_code: "+507",
        }, {
            dial_code: "+675",
        }, {
            dial_code: "+595",
        }, {
            dial_code: "+63",
        }, {
            dial_code: "+48",
        }, {
            dial_code: "+351",
        }, {
            dial_code: "+1 939",
        }, {
            dial_code: "+974",
        }, {
            dial_code: "+40",
        }, {
            dial_code: "+250",
        }, {
            dial_code: "+685",
        }, {
            dial_code: "+378",
        }, {
            dial_code: "+966",
        }, {
            dial_code: "+221",
        }, {
            dial_code: "+381",
        }, {
            dial_code: "+248",
        }, {
            dial_code: "+232",
        }, {
            dial_code: "+65",

        }, {
            dial_code: "+421",
        }, {
            dial_code: "+386",
        }, {
            dial_code: "+677",
        }, {
            dial_code: "+27",
        }, {
            dial_code: "+500",
        }, {
            dial_code: "+34",
        }, {
            dial_code: "+94",
        }, {
            dial_code: "+249",
        }, {
            dial_code: "+268",
        }, {
            dial_code: "+46",
        }, {
            dial_code: "+41",
        }, {
            dial_code: "+992",
        }, {
            dial_code: "+66",
        }, {
            dial_code: "+690",
        }, {
            dial_code: "+676",
        }, {
            dial_code: "+1 868",
        }, {
            dial_code: "+216",
        }, {
            dial_code: "+90",
        }, {
            dial_code: "+993",
        }, {
            dial_code: "+1 649",
        }, {
            dial_code: "+688",
        }, {
            dial_code: "+256",
        }, {
            dial_code: "+380",
        }, {
            dial_code: "+971",
        }, {
            dial_code: "+44",
        }, {
            dial_code: "+598",
        }, {
            dial_code: "+998",
        }, {
            dial_code: "+678",
        }, {
            dial_code: "+681",
        }, {
            dial_code: "+967",
        }, {
            dial_code: "+260",
        }, {
            dial_code: "+263",
        }, {
            dial_code: "+591",
        }, {
            dial_code: "+673",
        }, {
            dial_code: "+61",
        }, {
            dial_code: "+243",
        }, {
            dial_code: "+225",
        }, {
            dial_code: "+500",
        }, {
            dial_code: "+44",
        }, {
            dial_code: "+379",
        }, {
            dial_code: "+852",
        }, {
            dial_code: "+98",
        }, {
            dial_code: "+44",
        }, {
            dial_code: "+44",
        }, {
            dial_code: "+850",
        }, {
            dial_code: "+82",
        }, {
            dial_code: "+856",
        }, {
            dial_code: "+218",
        }, {
            dial_code: "+853",
        }, {
            dial_code: "+389",
        }, {
            dial_code: "+691",
        }, {
            dial_code: "+373",
        }, {
            dial_code: "+258",
        }, {
            dial_code: "+970",
        }, {
            dial_code: "+872",
        }, {
            dial_code: "+262",
        }, {
            dial_code: "+7",
        }, {
            dial_code: "+590",
        }, {
            dial_code: "+290",
        }, {
            dial_code: "+1 869",
        }, {
            dial_code: "+1 758",
        }, {
            dial_code: "+590",
        }, {
            dial_code: "+508",
        }, {
            dial_code: "+1 784",
        }, {
            dial_code: "+239",
        }, {
            dial_code: "+252",
        }, {
            dial_code: "+47",
        }, {
            dial_code: "+963",
        }, {
            dial_code: "+886",
        }, {
            dial_code: "+255",
        }, {
            dial_code: "+670",
        }, {
            dial_code: "+58",
        }, {
            dial_code: "+84",
        }, {
            dial_code: "+1 284",
        }, {
            dial_code: "+1 340",
        }]
    }
}
